[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/book/:isbn"
  to = "/.netlify/functions/book/:isbn"
  status = 200

[[redirects]]
  from = "/api/cover/:isbn"
  to = "/.netlify/functions/cover/:isbn"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*"
    X-Frame-Options = "DENY"
